# Generated by Django 4.2.9 on 2024-04-04 14:17

from django.db import migrations
from datetime import datetime
from django.utils import timezone
from django.contrib.auth.hashers import make_password


def add_users(apps, schema_editor):
    User = apps.get_model("users", "User")

    tz = timezone.get_current_timezone()
    now_datetime = datetime.now().replace(tzinfo=tz)

    User.objects.get_or_create(
        id=1,
        created_at=now_datetime,
        username='admin',
        email='admin@h.com',
        first_name='Admin',
        last_name='Adminskiy',
        password=make_password('111111'),
        role='administrator',
        is_superuser=True,
        is_staff=True
    )

    User.objects.get_or_create(
        id=2,
        created_at=now_datetime,
        username='vasya',
        email='vasya@h.com',
        first_name='Василий',
        last_name='Пупкин',
        password=make_password('zxc102938'),
        role='user',
        is_superuser=False,
        is_staff=True
    )
    User.objects.get_or_create(
        id=3,
        created_at=now_datetime,
        username='joe',
        email='joe@h.com',
        first_name='Джо',
        last_name='Блэк',
        password=make_password('mko091122'),
        role='user',
        is_superuser=False,
        is_staff=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_users),
    ]
