# Generated by Django 4.2.9 on 2024-04-10 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_city_country_file_street_city_сountry_id_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название события')),
                ('description', models.TextField(blank=True, verbose_name='Описание события')),
                ('started_at', models.DateTimeField(blank=True, verbose_name='Дата начала события')),
                ('ended_at', models.DateTimeField(blank=True, verbose_name='Дата окончания события')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на трансляцию')),
                ('is_offline', models.BooleanField(default=False, verbose_name='Оффлайн')),
                ('address_comment', models.TextField(blank=True, max_length=250, verbose_name='Как добраться')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.building', verbose_name='ID дома (адрес)')),
                ('event_specializations', models.ManyToManyField(blank=True, related_name='events', to='events.eventspecialization', verbose_name='Специализации')),
                ('files', models.ManyToManyField(blank=True, related_name='events', to='events.file', verbose_name='Файлы')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='events.event')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_format', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='online', max_length=16)),
                ('status', models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('canceled', 'canceled')], default='new', max_length=16)),
                ('event', models.ForeignKey(help_text='Конференция, на которую подписались', on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='events.event', verbose_name='ID конференции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='speaker', max_length=16)),
                ('event', models.ForeignKey(help_text='Конференция, на которую подписались', on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.event', verbose_name='ID конференции')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.participant', verbose_name='ID участника')),
            ],
            options={
                'verbose_name': 'Спикер',
                'verbose_name_plural': 'Спикеры',
            },
        ),
        migrations.AddConstraint(
            model_name='speaker',
            constraint=models.UniqueConstraint(fields=('participant', 'event'), name='speaker_user_event'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='participant_user_event'),
        ),
    ]
