# Generated by Django 4.2.9 on 2024-04-09 19:15
from django.db import migrations


def add_anketa(apps, schema_editor):
    Anketa = apps.get_model('events', 'Anketa')

    obj, _ = Anketa.objects.get_or_create(
        first_name='Николай',
        last_name='Петров',
        email='nikolay@yandex.ru',
        phone='89236505465',
        job_position='Яндекс',
        job_title='Backend Разработчик',
        experience='От 3 лет',
    )
    obj.users.add(1)
    obj.event_specializations.add(3)
    obj.event_specializations.add(4)
    obj.event_specializations.add(9)
    obj.event_specializations.add(10)
    obj.event_specializations.add(11)
    obj.interests.add(1)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_anketa'),
    ]

    operations = [
        migrations.RunPython(add_anketa),
    ]
