# Generated by Django 4.2.9 on 2024-04-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_participant_speaker_speaker_speaker_user_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anketa',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='street_id',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='сountry_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='city_id',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='anketa',
            name='event_specializations',
            field=models.ManyToManyField(related_name='anketa', to='events.eventspecialization', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='interests',
            field=models.ManyToManyField(related_name='anketa', to='events.interest', verbose_name='Интересы'),
        ),
    ]
