# Generated by Django 4.2.9 on 2024-04-12 04:06

from django.db import migrations


def add_data(apps, schema_editor):
    Country = apps.get_model("events", "Country")
    Country.objects.get_or_create(
        id=1,
        name='Russia'
    )

    City = apps.get_model("events", "City")
    obj_country1 = Country.objects.get(id=1)
    City.objects.get_or_create(
        id=1,
        name='Москва',
        country=obj_country1,
    )

    City.objects.get_or_create(
        id=2,
        name='Санкт-Петербург',
        country=obj_country1,
    )

    City.objects.get_or_create(
        id=3,
        name='Сочи',
        country=obj_country1,
    )

    Street = apps.get_model("events", "Street")
    obj_city1 = City.objects.get(id=1)
    Street.objects.get_or_create(
        id=1,
        name='Арбат',
        city=obj_city1,
    )

    Street.objects.get_or_create(
        id=2,
        name='Тверская',
        city=obj_city1,
    )

    obj_city2 = City.objects.get(id=2)
    Street.objects.get_or_create(
        id=3,
        name='Малая Содовая',
        city=obj_city2,
    )

    Street.objects.get_or_create(
        id=4,
        name='Большая Морская',
        city=obj_city2,
    )

    obj_city3 = City.objects.get(id=3)
    Street.objects.get_or_create(
        id=5,
        name='Навагинска',
        city=obj_city3,
    )

    Street.objects.get_or_create(
        id=6,
        name='Нагорная',
        city=obj_city3,
    )

    Building = apps.get_model("events", "Building")
    obj_street1 = Street.objects.get(id=1)
    Building.objects.get_or_create(
        id=1,
        name='32',
        street=obj_street1,
        latitude=55.749096,
        longitude=37.589599,
    )

    obj_street2 = Street.objects.get(id=2)
    Building.objects.get_or_create(
        id=2,
        name='3',
        street=obj_street2,
        latitude=55.757369,
        longitude=37.612991,
    )

    obj_street3 = Street.objects.get(id=3)
    Building.objects.get_or_create(
        id=3,
        name='8',
        street=obj_street3,
        latitude=59.934619,
        longitude=30.337787,
    )

    obj_street4 = Street.objects.get(id=4)
    Building.objects.get_or_create(
        id=4,
        name='55',
        street=obj_street4,
        latitude=59.931287,
        longitude=30.302339,
    )

    obj_street5 = Street.objects.get(id=5)
    Building.objects.get_or_create(
        id=5,
        name='9Д',
        street=obj_street5,
        latitude=43.587912,
        longitude=39.723631,
    )

    obj_street6 = Street.objects.get(id=6)
    Building.objects.get_or_create(
        id=6,
        name='14',
        street=obj_street6,
        latitude=43.578198,
        longitude=39.730078,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_users_anketa_user_and_more'),
    ]

    operations = [
        migrations.RunPython(add_data),
    ]
