# Generated by Django 4.2.9 on 2024-04-15 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20240412_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_file', models.CharField(max_length=50, verbose_name='Тип файла')),
            ],
            options={
                'verbose_name': 'Тип файла',
                'verbose_name_plural': 'Типы файла',
            },
        ),
        migrations.AddField(
            model_name='speaker',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('canceled', 'canceled')], default='new', max_length=16),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_comment',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Как добраться'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала события'),
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='events.typeoffile', verbose_name='Тип файла'),
            preserve_default=False,
        ),
    ]
