# Generated by Django 4.2.9 on 2024-04-16 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_typeoffile_speaker_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_anketa', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
